baseURL = "https://benamiller.github.io/"
title = "Ben Miller - Blog"
paginate = 5
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

languageCode = "en-us"
defaultContentLanguage = "en"

[minify]
  disableXML = true
  minifyOutput = true
