baseURL = "https://benamiller.github.io/"
title = "Ben Miller - Blog"
paginate = 5
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
languageCode = "en-us"
defaultContentLanguage = "en"

[minify]
  disableXML = true
  minifyOutput = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  custom_css = []
  custom_js = []

[params.assets]
  disableHLJS = true
  customJS = [
    "https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js",
    "https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js",
    "/js/katex.js"
  ]
  customCSS = ["https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css"]

[params.math]
  enable = true
